name: generate pacman game
on:
  schedule:
    # Run automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: # Allows manual triggering
  push: # Runs on every push to the main branch
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub
          pip install pyyaml
          pip install requests
      - name: Run generate_pacman.py
        run: python .github/workflows/generate_pacman.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Pac-Man contribution graph"
          commit_options: '--signoff'
          create_pull_request: false
